!#/bin/bash

gpg --batch --homedir /tmp/onlyoffice-gnupg \
    --no-default-keyring --keyring /usr/share/keyrings/onlyoffice.gpg \
    --keyserver hkps://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5 \
chmod 644 /usr/share/keyrings/onlyoffice.gpg \
rm -rf /tmp/onlyoffice-gnupg

echo 'deb [signed-by=/usr/share/keyrings/onlyoffice.gpg] https://download.onlyoffice.com/repo/debian squeeze main' | sudo tee -a /etc/apt/sources.list.d/onlyoffice.list
apt-get update
apt-get install onlyoffice-desktopeditors
# wget -O /tmp/onlyoffice-desktopeditors.deb https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors_amd64.deb 
# dpkg -i /tmp/onlyoffice-desktopeditors.deb 
# rm /tmp/onlyoffice-desktopeditors.deb 
echo 'ONLYOFFICE_BIN=$(which onlyoffice-desktopeditors DesktopEditors 2>/dev/null | head -1)' >> /home/${XRDP_USER}/.xsession 
# echo 'if [ -z "$ONLYOFFICE_BIN" ]; then' >> /home/${XRDP_USER}/.xsession 
# echo '  ONLYOFFICE_BIN=$(find /opt /usr/bin -name "onlyoffice-desktopeditors" -o -name "DesktopEditors" 2>/dev/null | head -1)' >> /home/${XRDP_USER}/.xsession 
