[program:chromium]
command=/usr/bin/chromium --no-sandbox --disable-gpu --disable-dev-shm-usage --start-maximized --kiosk %(ENV_STARTING_WEBSITE_URL)s
autostart=%(ENV_AUTO_START_BROWSER)s
autorestart=true
user=root
environment=DISPLAY=:10